server:
  port: 7070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    password: Rhenzour26
    url: jdbc:mysql://localhost:3306/banquedb
    username: root
  jpa:
    show-sql: true
